In [48]:
import numpy as np
import GPy
import math

In [49]:
last_state=np.array([[-0.03433176, -5.16552294,  0.99939083, -0.0348995 ,  6.90233291,
             5.11905123],
           [-0.1451667 , -5.14079246,  0.99939083, -0.0348995 ,  6.99009626,
             5.10679236],
           [-0.1980269 , -5.11772757,  0.99756405, -0.06975647,  6.9874905 ,
             5.09024185],
           [-0.22321358, -5.08962549,  0.99756405, -0.06975647,  7.0128794 ,
             5.07051226],
           [-0.2174193 , -5.04679767,  0.9945219 , -0.10452846,  7.01022064,
             5.05732956],
           [-0.22358937, -5.00886088,  0.99254615, -0.12186934,  7.00870113,
             5.04514437],
           [-0.13832238, -4.96395747,  0.99026807, -0.1391731 ,  7.00649795,
             5.04038418],
           [-0.06820388, -4.91761054,  0.98768834, -0.15643447,  7.00418579,
             5.05927716]])

In [53]:
x = last_state[:,0]
y = last_state[:,1]
length = last_state[:,2]
width = last_state[:,3]
theta = [math.atan2(sin,cos) for sin,cos in zip(last_state[:,4],last_state[:,5])]

In [56]:
col_x = np.array(x).reshape(-1,1)
col_y = np.array(y).reshape(-1,1)
col_theta = np.array(theta).reshape(-1,1)


[[-0.03433176]
 [-0.1451667 ]
 [-0.1980269 ]
 [-0.22321358]
 [-0.2174193 ]
 [-0.22358937]
 [-0.13832238]
 [-0.06820388]]


In [34]:
Input1D = np.array(np.arange(0,1.6,0.2)).reshape(-1,1)
print(Input1D)

[[0. ]
 [0.2]
 [0.4]
 [0.6]
 [0.8]
 [1. ]
 [1.2]
 [1.4]]


In [35]:
k = GPy.kern.Matern32(1)
m1 = GPy.models.GPRegression(Input1D,col_x,kernel=k)
m1.optimize()

In [42]:
test_input = np.array([1.6]).reshape(-1,1)
print(test_input)

[[1.6]]


In [43]:
m1.predict(test_input)

(array([[-0.02783341]]), array([[0.00188701]]))

In [47]:
k = GPy.kern.Matern32(1)
m2 = GPy.models.GPRegression(Input1D,col_y,kernel=k)
m2.optimize()
m2.predict(test_input)

(array([[-4.87186505]]), array([[5.6880395e-05]]))

In [64]:
index = np.asarray([np.zeros((6,1))+i for i in range(4)]).reshape(-1,1)
# print(index)
# print(type(index),len(index))